### PR TITLE
Some improvements (read description)

### PR DESCRIPTION
**Pull request by Jolty95**
italian.h: improve translation and correct mistakes by nop90
readme.md: update with the new info
main.cpp: fix the previous PR
languages: fix the indentation because it's easier to read them with the PR's indentation using notepad++ than before :)
nand side: small note to use python 2 (if python 3 is installed too)
.travis.yml: @Robz8  I know you don't use it, but keep it if you don't mind cause it's usefull at least for me

### CODE REVIEW

**Comment by Jolty95** [comment]
PS: Use split to review the text ;)

**Comment by Robz8** [comment]
You can remake the pull request after I merged the citro branch to master. :)

**Comment by Jolty95** [comment]
What should I do? ;_;
When you merge the citro branch, should I add that commits to my fork and open again a PR?

**Comment by Robz8** [comment]
I think so.

**Comment by Jolty95** [comment]
If not, I can always push directly all changes again in one commit if you want :)

**Comment by Robz8** [comment]
OK, the citro branch is merged.

**Pull request merged**
