### PR TITLE
Fix boxarts for flashcard not downloading

### PR DESCRIPTION
**Pull request by Jolty95**
Need a tester!

### CODE REVIEW

**Comment by Robz8** [comment]
There was actually a problem in my end.
Box art for flashcards is being read from "/_nds/twloader/boxart/" just fine.

**Comment by Jolty95** [comment]
Oh that's why I say I need a tester hahaha
So should I close here and revert in my end, right? 
It's a problem that I cannot help you with flashcards things tbh... :(

**Comment by Robz8** [comment]
Ok, I thought there was a problem in my end, but there wasn't.
Yeah, please revert.

**Comment by Jolty95** [comment]
I you don't mind, I'll only do things about GUI side. No twl/flashcard :) 
(Better for all us to help in something I can test :P )

**Pull request closed without merging**
