### PR TITLE
Add delete mode, delete queue and new update system

### PR DESCRIPTION
**Pull request by Jolty95**
EDIT: The crash is only present if you have exactly (only found the bug with this number), 12 roms/.ini files on memory. I mean, you have 15, delete one, go to game 12 of 14 and it crash.

#### What's new?
-Delete code now is assigned to X button (only tested on DSi theme)
-Move boxarts to boxart\flashcard and boxart\slot1 (sd rom boxarts are still on boxart folder)
-Modify a bit boxart download code adding a new enum.
09/05/17
-Add some code to prevent double press on X button. This would avoid also accident deletions.
-Render boxart cont in dialogbox
10/05/17
-Add more code to delete mode 
-Add a delete queue pressing L+X
11/05/17
-Now you can delete only one or a queue
-Simplify a lot delete code using a new internal method
12/05/17
-Add a new selective update method (WIP and really need more help to add it since this PR it's too huge to just add it myself)

#### What is fixed?

-Some bugs affecting boxarts and it location
09/05/17
-Display correctly dialogbox of boxarts
11/05/17
-Fix a bug in delete mode affecting boxarts
12/05/17
-Some errors of yesterday's commit iirc

#### Where have you tested it?

Only on OLD 3DS XL + A9LH + Luma + 11.4 without flashcard
Only with .nds and .ini files (with and without banner and with and without boxarts)
Boxarts have been tested by TID and filename (only one of them, in order filename -> TID -> no boxart)
Unable to test with real flashcard banner files (atm)
Only tested on DSi theme. (X and L+X are not added to others themes yet until DSi theme is perfectly done without issues)

#### Why is not ready yet?

It's almost ready. There are some bugs yet
a) Crash after deleting games if you go to position 12 (only after deleting)
b) Strange boxart after curpostition+1
c) Not all selective update method is fully completed

*** 
#### Pull Request status
- [x]  This PR has been tested using latest DEVKITPRO, DEVKITARM, SFILLIB, SF2DLIB, LIBNDS and Citro3DS.  

_(Do not edit after this point)_
- [x]  This PR is fully documented.
- [x]  This PR has been tested before sending.
- [x]  This PR follows C style and convention.

### CODE REVIEW

**Comment by deadair3210** [comment]
Are boxartas going to be moved automatically or would the user have to do this manually

**Comment by Jolty95** [comment]
@deadair3210 manually. 
It's the best for users and I'll lock this conversation until development of this PR has finished ;)

**Comment by Robz8** [comment]
If this gets merged, I'll see about adding a confirmation screen for deleting a game.

**Comment by Jolty95** [comment]
I like the idea of confirmation screen :)
Also, I didn't wanted .sav files to get deleted. If user wants to delete them, I rather they do themselves instead (imagine they delete game(s) by accident)

Today I'll try to fix the annoying bug with less than 10 themes and add the multi delete option too

**Comment by maorninja** [comment]
This is a nice pr. May I please review it?

**Comment by Jolty95** [comment]
@maorninja I'm trying to make you reviewer of this PR but I'm unable to do it :( Only Robz is displaying on list

**Comment by Jolty95** [comment]
I've a question. My local repo (and my fork) doesn't have your new additions but we are not in conflicts with the base branch. Is there any problem later when this gets merged? I think this will take me a bit more of time (maybe one more day) plus I cannot debug all code just myself

**Comment by Robz8** [comment]
I don't think there will be any problem when this gets merged.

Hmm, let's do B. I can wait a bit more.

**Comment by Jolty95** [comment]
I've change the OP of this PR. Please read it when you have any time :P 
I'll also add tomorrow or this afternoon a fix to my issue (about fallback region) if not, I'll finish to add the _new secret method_ and tomorrow this would be ready to merge (appart from the delete bugs)

**Comment by Jolty95** [comment]
I've uploaded a "beta" here:
https://github.com/Jolty95/TWLoader-update/blob/master/beta/TWLoader.cia

**Comment by Robz8** [comment]
Tested the beta.
Dialog box now disappears if box art checking/download is done. I never knew why it wouldn't disappear in the first place.

**Comment by Jolty95** [comment]
@Robz8 so, it's working that fine?

**Comment by Robz8** [comment]
@Jolty95 Deleting a game works fine, so I think so.

**Comment by Jolty95** [comment]
@Robz8 I've thinking about this PR...
Missing things:
-a) check if NAND side needs update.
-b) check if prebuilds needs update.
-c) fix the crashing bug in delete mode when, after deleting, you go to position 12~
-d) fix the weird boxart when you have less than 20 games (always show a n + 1 boxart in right)
-e) fix this: https://github.com/Robz8/TWLoader/issues/267 it's really annoying for me at least
-f) need some help debuing L+X mode

Explanations:
-a) EXAMPLE: imagine in v3.1.0 you update NAND SIDE too. You push a update of it and it's a mandatory update. Imagine now, that you update GUI to v3.2.0 but NOT update NAND SIDE (not neccesary in this example). TWLoader will ONLY DOWNLOAD AND INSTALL GUI side. Imagine now, you update nand and gui in 3.3.0. TWLoader will download gui and nand too. 

-b) This is the same as before. If prebuilds change (one of them or any, it's the same code tho), TWLoader will autodownload them too only if necessary to update them.

-c) Explained before. Dunno why it crash. I've found in code you added something to display first the current boxart. Later, the next boxart and later the prev boxart. And there are some "master" positions like 6 and 12 iirc. Maybe crash it's because that (?) I need help debuging this (easy using `Log("whatever");`
 
-d) If you have 15 roms, delete one game, you have 14 roms right? Yes, but 15 boxarts, boxart nº 14 is duplicated in right (weird as fuck)

-e) European region fallback when spanish is not found is buggy af too. Not tested on others regions but seems to work OK on USA regions

-f) Sometimes L+X adds, sometimes it reset cursor but not adds, sometimes it reset cursor but adds, and sometimes it do all at the same time (all is written on logs). Need to control this to prevent double 'cause if one game is added to delete list and you press L+X, it is unmarked but if you press ONLY ONE TIME, sometimes it mark and unmark at the same time. Too buggy and need help 'cause this is the biggest PR I've ever done and It's too much work for just me to debug all haha


PS about a) and b) in order to update NAND / PREBUILDS, it will always needed to push a new gui side. I mean, in my model, you cannot ONLY update prebuilds or nand. Without a new gui, we cannot release only a NAND (just like we are doing rn :P )

**Comment by Robz8** [comment]
So should I merge?

**Comment by Jolty95** [comment]
I'd like to finish at least leter a) to make update system works without issues for users, so we can implement prebuilds selective update later without bothering anyone ;) 

Or merge if you want, I mean, it's your repo :P 
For now, I'll change title to make it looks better in master history graph

**Comment by Robz8** [comment]
Yeah, I may not release a new version too soon anyways.

**Comment by Jolty95** [comment]
Remember to change JSON url to update repo 
https://raw.githubusercontent.com/Jolty95/TWLoader-update/master/update.json

**Comment by maorninja** [comment]
No, as in, @Jolty95, why did you add that white space?

**Comment by Jolty95** [comment]
@maorninja aaaaaaaa I see xD That's why I was cleaning it a bit and that was an accident :P 
BTW, what "as in" mean?

**Comment by maorninja** [comment]
I was talking about this "maorninja commented on gui/source/download.cpp in f95a845 10 hours ago
Was this necessary?
  Collaborator
Jolty95 replied 9 hours ago
It's not finished yet."

**Pull request merged**
