### PR TITLE
fix incorrect location of version display code

### PR DESCRIPTION
**Pull request by bakawun**
Please test if this works before merging.

### CODE REVIEW

**Comment by Robz8** [comment]
Still getting the error.

**Comment by Robz8** [comment]
Does the source tree have to be in a specific location?

**Comment by bakawun** [comment]
in FBI it is here: https://github.com/Steveice10/FBI/blob/master/source/ui/ui.c#L152

**Comment by Robz8** [comment]
Thanks anyways, but I'm sticking with manual version numbers for now.

**Comment by tetsuo55** [comment]
revert https://github.com/Robz8/TWLoader/commit/662727e304c6bd98fa66597d6de48a4caeffa475 for now

**Comment by Robz8** [comment]
Nah. I can set the version in the Makefile.

**Comment by bakawun** [comment]
In the PR i sent before i know 100% the makefile version number generation works.
It is the code that shows the version number on the settings screen that is not working for some reason.

**Comment by bakawun** [comment]
I think we are missing the code and/or dependency to read our internal version numbers

**Comment by bakawun** [comment]
Actually if you manually enter the numbers in the makefile instead of using the git command then that must mean the git command is failing.

Did you compile from a git clone directory?

What happens when instead of make you run 
git describe --tags --abbrev=0

**Comment by Robz8** [comment]
'git' is not recognized as an internal or external command,
operable program or batch file.

**Comment by bakawun** [comment]
Okay I will update the compiler instructions so you (and anyone else) can get git working.

**Pull request closed without merging**
