### PR TITLE
No more crash when updating NAND side

### PR DESCRIPTION
**Pull request by Jolty95**
Changelog:
 

- [x]  TWLNand side is not causing more crashes when updating.
- [X]   Also, autodownload have been fixed (that's mean that v3.2.1 have the bug, so, when installing new v3.2.2 or v3.3 will still crash but after that version it WON'T!!)

- [X]    Press Select button and have fun with that new button.
- [X]    cart_ntr.png has been optimized too.
- [x]     New button only works if you press SELECT before launching!! (Need to find how to make it automatic tho)

This PR have two bugs that I don't know how to solve them. First, if user doesn't press Select before launching the rom, LoadPerGameSettings doesn't load (and I guess that other per-game settings neither)
Second bug: if .ini doesn't exist and you launch a rom, notificationled is off because LoadPerGameSettings have a bug (read the paragraph above)

### CODE REVIEW

**Comment by Margen67** [comment]
Maybe you could also add this to your PR and optimize it? https://github.com/Robz8/TWLoader/pull/156/files

**Comment by Jolty95** [comment]
If this is ok for you, I'm going to download your image, upload in my PR and credit you. Is ok like this? :)

**Comment by Margen67** [comment]
Yes.

**Comment by Jolty95** [comment]
Done 👍

**Comment by tetsuo55** [comment]
@Jolty95 for next time. You could have cherry picked @Margen67 's change by doing this:
git remote add margen67 url_to_margen_repo
git fetch margen67
git cherry-pick 7e2e7904e15b17d3a174b77721d83dad4294df76

then edit the png and commit your own change

**Comment by Jolty95** [comment]
@tetsuo55 I asked before doing it...

**Comment by bakawun** [comment]
@tetsuo55 has a point here.

I agree you discussed how to handle it beforehand.
but when or if something like this happens again in the future you can easily cherry pick and retain original ownership.

**Comment by Jolty95** [comment]
Ok, stop. No discussion here. I asked before doing it so no discussion here please.

**Comment by bakawun** [comment]
ok.

I checked the code and 7zip for the default auto-update values and found all to be set to "off"

so for the people who where having issues with auto updating they either had old settings files or enabled auto update manually.

so I don't have any changes to add to this

**Pull request merged**
