### PR TITLE
Optimized all png images with pingo

### PR DESCRIPTION
**Pull request by bakawun**
http://css-ig.net/pingo
command used: pingo -s4 file.png
All images optimized with pingo 0.58 alpha 5 except:

The following images where optimized with 0.58 stable
because i was unable to disable to auto-jpg conversion
* gui/romfs/graphics/r4/bckgrd_1.png.jpg
* gui/romfs/graphics/wood/gbatemp/lower_screen.png.jpg
* gui/romfs/graphics/wood/gbatemp/upper_screen.png.jpg

The following images crashed pingo
* gui\romfs\graphics\r4\bckgrd_2.png
* gui\romfs\graphics\settings\screen.png
* gui\romfs\graphics\blank_128x115.png
* gui\romfs\graphics\bottom.png
* gui\romfs\graphics\boxart_null.png
* gui\romfs\graphics\dialogbox.png
* gui\romfs\graphics\start_border.png

### CODE REVIEW

**Comment by bakawun** [comment]
Savings:
Total project size (including the .git folder):
31.408.779 bytes before
31.124.474 bytes after
   284.305 bytes saved

**Comment by Jolty95** [comment]
Remember that we're using SFIL'S PNG loading method, just telling you in case something is converted to .JPG

**Comment by tetsuo55** [comment]
I reverted all jpg conversions and used another version that does not convert to jpg on those befoe committing

**Comment by Jolty95** [comment]
Have you compiled and tested? Because using JPG really crash the console (I tested a lot of times thinking the .png file was a PNG and was a jpg)

**Comment by tetsuo55** [comment]
There are no jpg's, but i did not compile yet because i still need feedback on https://github.com/Robz8/TWLoader/pull/183

**Comment by Jolty95** [comment]
It's @Robz8 decision to merge a PR or not, that's why I send PR too instead of pushing directly :P You need his approve first :)

**Comment by bakawun** [comment]
Any file that was converted to jpg was corrected back to png.
I have not yet made a successfull compile because i am still stuck on the dev env setup process.

**Comment by maorninja** [comment]
Me, personally, I really think that we should also allow .JPG, as if you guys want to cut down build size, having .JPG for some images are perfect.

**Comment by Robz8** [comment]
Except the image quality will be bad.

**Comment by bakawun** [comment]
This pull request has only lossless optimizations, so the image quality is the same.

Some images could be smaller through the use of jpg and the difference in quality is very small, possibly only visible with a image diff tool.

**Comment by bakawun** [comment]
@Robz8 i suggest you merge this PR before continuing on.
Particularly because we can use pingo to auto-decide if the jpg file will be smaller or not

**Pull request merged**
