### PR TITLE
Add the 3dsx demo to the build process

### PR DESCRIPTION
**Pull request by bakawun**

### CODE REVIEW

**Comment by Robz8** [comment]
Do you know of a way for the "is3DSX" bool value to be set to true, only for 3DSX version?

**Comment by Jolty95** [comment]
@Robz8 I think I can do it if he doesn't know :)

**Comment by Robz8** [comment]
Thanks.

**Comment by Jolty95** [comment]
There is not needed to thanks me. You know I'm helping you with TWLoader for fun :)

**Comment by bakawun** [comment]
something like this should work

makefile changes: 

First we globally set it to false
IS3DSX := false

under .PHONY: we add this to 3dsx

3dsx: export IS3DSX := true
      $(BUILD)
     @$(MAKE) --no-print-directory -C $(BUILD) -f $(CURDIR)/Makefile 3dsx

main.cpp changes:
bool is3DSX = $(IS3DSX);

**Comment by Jolty95** [comment]
Late. I have already done it but haven't pushed yet

**Comment by bakawun** [comment]
you should have told me

**Comment by bakawun** [comment]
https://github.com/Robz8/TWLoader/pull/196/commits/30ed8ae8fcbbd2d0e565a76224c0894e11eeaab7

very nicely solved

**Comment by Jolty95** [comment]
It's strange. I've compiled and tested with citra 2 times (3dsx version) and demo version shows, but I've recompiled again and now 3dsx is the same as cia. Dunno why

**Comment by bakawun** [comment]
Try giving the 3dsx and cia seperate output folders

**Comment by Jolty95** [comment]
COMPILE_3DSX seems to be always cero :(

**Comment by Jolty95** [comment]
I found a "solution"
It can be improved but this is better than nothing btw

**Comment by bakawun** [comment]
it should work if you use export in the makefile

cia: export COMPILE_3DSX=0
3dsx: export COMPILE_3DSX=1

**Pull request merged**
