### PR TITLE
apply astyle

### PR DESCRIPTION
**Pull request by bakawun**
Apply astyle to improve readability and consistency.

astyle -V = Artistic Style Version 2.06
https://sourceforge.net/projects/astyle/files/

commands used
astyle -r --options=astyle.ini TWLoader\gui*.cpp
astyle -r --options=astyle.ini --keep-one-line-blocks TWLoader\gui*.h

settings used in astyle .ini:

--indent=spaces=4 --style=kr
--indent-switches --indent-namespaces --indent-col1-comments
--max-instatement-indent=65
--attach-inlines
--pad-header --pad-oper --unpad-paren
--align-pointer=type --align-reference=type
--close-templates
--add-brackets
--convert-tabs
--lineend=windows --preserve-date
--suffix=none
--ignore-exclude-errors --ignore-exclude-errors-x
--formatted

### CODE REVIEW

**Comment by bakawun** [comment]
Updated to current master head

**Comment by GerbilSoft** [comment]
While having a consistent coding style is a good idea, applying it all at once with a million changes can cause problems when trying to debug changes.

I'd recommend improving style when editing individual functions instead of just doing the whole thing all at once.

**Comment by tetsuo55** [comment]
@Robz8 This PR has to rebased every time something else is committed, could you merge this one quickly?
We can always discuss the exact settings used for astyle and change them at any time.

No code changes here, it is all cosmetic.

**Comment by tetsuo55** [comment]
@GerbilSoft we could opt out of the tabs to spaces and the changes would be minimal

**Comment by bakawun** [comment]
@GerbilSoft I think there are bigger problems with regards to debugging than just the coding style.
It does break blame until more commits are made.

I think the line endings are the biggest change (touching every line on every file) we could skip those and keep just the lines that that actually got reformatted visibly

**Comment by bakawun** [comment]
@GerbilSoft maybe something like this: https://github.com/bakawun/TWLoader/commit/052ef10b447b51a6ac11e52f0ce7f97cc58f123f

**Comment by Jolty95** [comment]
I agree with @GerbilSoft . IMO if this get merged will make us too difficult to diff changes because all repo history will be overwriten

**Comment by bakawun** [comment]
i will close this and open an issue instead

**Pull request closed without merging**
