### PR TITLE
Improve the Start and per-game settings menu a bit; handle "unknown" carts; rmkdir().

### PR DESCRIPTION
**Pull request by GerbilSoft**
This PR will need some testing with the CycloDS cartridge, since I don't have one available.

Main changes:
* Split the Start and per-game settings dialog into a separate function.
* Improve button drawing: Use an array of structs, center-align text correctly.
* Attempt to support cartridges with invalid banners. If FSUSER_CardSlotIsInserted() returns 1, the cartridge will be startable, even if the banner can't be loaded.
* Fix some weird artifacting with the Slot-1 boxart when inserting/removing a cartridge.
* Added an rmkdir() function to recursively mkdir() and use it for the ROMs directories.

@Robz8 Can you test the CycloDS with this PR before merging and see if it works?

### CODE REVIEW

**Comment by Robz8** [comment]
For CycloDS to work, a detectable DS cartridge will have to be put in first, then take it out, and put the CycloDS cart in. It will show as "Unknown Cartridge", but TWLoader is now running at half-speed.

**Comment by GerbilSoft** [comment]
Seems odd that it isn't detected in some cases...

The only other option would be to just remove the block on starting Slot-1 with no cartridge inserted.

Also, TWLoader running at half-speed? That might be because when it says "Unknown Cartridge", it continuously polls the slot. In that case, don't merge this yet. It'll probably be better to just allow launching Slot-1 even if nothing is detected.

**Comment by Margen67** [comment]
What about a confirmation that says "No cartridge detected. Launch anyway?"

**Comment by Robz8** [comment]
The DS/DSi boot screen says to "insert a cartridge" if it's not in.

**Comment by GerbilSoft** [comment]
@Robz8 I changed the cartridge insert detection to poll twice a second for up to 5 seconds. That should improve the responsiveness when inserting a CycloDS cartridge. Can you test it out to see if it works any better now?

**Comment by Robz8** [comment]
Still going half-speed when the CycloDS is inserted.

**Comment by GerbilSoft** [comment]
Pushed a new commit that should reduce Slot-1 boxart loading. (I think that's what caused the half-speed issue.)

Strangely it's now freezing for about 1s when inserting a 3DS cartridge. Not sure why.

**Comment by Robz8** [comment]
The new commit worked! It's not half-speed anymore.

**Pull request merged**
