### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by Jolty95**
@Robz8 this ( ec1bf37 ) fix a problem in "standar" DSi menu rom select causing icons boxart and all layout be moved but R4 theme rom loading doesn't work. Example. if your game rom is number 5, in R4 theme, pergame settings are load for game number 5 BUT rom loading is for number 0 (first game in list).

### CODE REVIEW

**Comment by Margen67** [comment]
How do you optimize images?

**Comment by Jolty95** [comment]
@Margen67 copy/paste from Gerbilsoft:

@Jolty95 I've been using OptiPNG with options -o7 -nc. The -nc option tells it not to reduce the color palette. I've had issues with sf2d mangling paletted PNG images, so I have to use -nc to prevent it from reducing to paletted. (Unfortunately, that means it isn't as optimized as it could be.)

**Comment by Margen67** [comment]
Maybe that should be added somewhere like CONTRIBUTING.MD so all images added to the repo are optimized?

**Comment by bakawun** [comment]
with http://css-ig.net/pingo i can get them down even more, up to 70%

**Comment by Jolty95** [comment]
we don't want to reduce too much the palette

**Comment by bakawun** [comment]
try the various options and see what happ[ens, i see almost no difference befoe and after

**Comment by Jolty95** [comment]
this is not the priority of this PR. I'm fixing some bugs atm

**Comment by bakawun** [comment]
To end that discussion.
Afaik pingo is the strongest compressor for PNG (and jpg) while maintaining maximum compatibility.
Come back to it at a later time to see which options will work for twloader.

**Pull request merged**
