### PR TITLE
Improve performance, reduce memory leaks, clean up code.

### PR DESCRIPTION
**Pull request by GerbilSoft**
This PR changes a good amount of the code layout, which is why I'm sending it now before you make any more commits that need manual merging here.

Most of these changes reduce duplicated code and/or memory leaks. Here's a basic overview:
* Use arrays instead of individual variables where applicable. bannerandboxart.h is no longer needed.
* Consolidated repeated code by either splitting them into functions or factoring out what's different between the blocks.
* Optimized icon loading. Among other things, the palette is converted first, then each pixel is looked up in the palette.
* Improved banner loading. grabText() now returns a vector<string>, which contains the split-up banner lines.
* Banner lines are now properly centered.
* Disabled the .3dsx build, since it isn't usable.
* Added a proper check for "fully charged but still plugged in". This uses PTM:GetAdapterState, which ctrulib doesn't support and 3dbrew incorrectly lists as identical to PTM:GetBatteryLevel.
* Split all download and update code into a separate file, download.cpp.
* Fixed lots of memory leaks and other random bugs.

I haven't been able to properly test it with my R4i SDHC Dual Core due to the various flash card changes, but it does work with Sonic Rush via nds-bootstrap.

EDIT: This is a rather large PR. If you're still working on the flash card changes and don't want to merge this until that's done, let me know so I can merge everything after.

### CODE REVIEW

**Comment by Robz8** [comment]
3DSX build shouldn't be disabled, because it allows testing on Citra.

**Comment by GerbilSoft** [comment]
Ah, wasn't aware of that.

**Comment by Robz8** [comment]
I'm getting a crash while testing on hardware.

With Wifi on:
Crashes with "Checking box art." as the last line in the log.

With Wifi off:
************** Log file created at 18:07 **************
Method: <Main.Font loading> :
		Message:<Fonts load correctly>
Method: <Main.Verfile (ROMFS)> :
		Message: <Successful reading ver from ROMFS> 	Additional info:<Ver. 2.3.1   >
Method: <Main.LoadSettings> :
		Message:<Settings load successfully>
Method: <LoadColor()> :
		Message:<Colors load successfully>
Method: <LoadMenuColor()> :
		Message:<Menu color load successfully>
Method: <Main.sf2d_textures> :
		Message:<Textures load successfully>
Method: <Main.dspfirm> :
		Message:<DSP Firm found!>
Method: <Main.music> :
		Message:<Custom music file found!>
Method: <WifiStatus> :
		Message: <No Internet connetion active found> 	Additional info:<18:07>

**Comment by Robz8** [comment]
Are the latest changes working for you?

**Pull request merged**
