### PR TITLE
Add option to switch between bootstrap release and unofficial

### PR DESCRIPTION
**Pull request by Jolty95**
Now you can switch between release and unofficial bootstrap. 
PS: File must exist otherwise a white screen will appear

Release: release-bootstrap.nds
Unofficial: unofficial-bootstrap.nds

Also downloading boxarts for flashcard games has been fixed! Thanks @Favna for helping me debugging it :)

Also, bootstrap version is displayed!

### CODE REVIEW

**Comment by Favna** [comment]
Just occurred to me that a majority of the community has the folder `cias` on root after following plailect's guide as they are instructed to make this folder at [installing arm9loaderhax Section 1 - Prep Work Step 2](https://3ds.guide/installing-arm9loaderhax#section-i---prep-work)

Perhaps it would be a good idea to use that as the cia folder I reported on earlier? If it doesn't exist for the small minority that don't have it then it can just be created.

**Comment by Jolty95** [comment]
The problem is that a lot of users complain about having a "lot" of folders on root, that's why was moved to `SD:\_nds\twloader\`

**Comment by Favna** [comment]
ahahahahh yeah I would be one of those people - but I'm fairly certain the majority of people have and keep the cias folder there regardless.

Obviously I cannot say for certain though.

**Comment by Jolty95** [comment]
Me for example I don't have that folder hahaha
Also some users still use emunand ( 👎 ) or doesn't have A9LH installed (double 👎 ) so they didn't even know that folder exist. For now, I'll keep the cia folder in `SD:\_nds\twloader\` and if I have time, maybe I'll add a if statement to download in `SD:\cia\` if that folder previusly exist :)

**Comment by Jolty95** [comment]
@Robz8 I have noticed that fread is printing some garbage on lines: 508, 528, 546 and 561 of download.cpp. Too tired to fix it now. Would you mind to fix it please?

**Pull request merged**
