### PR TITLE
No more autodownload problems.

### PR DESCRIPTION
**Pull request by Jolty95**
download.cpp: fix the problem that always TWLoader wants to autodownload new version
main.cpp: add search function for flashcard too. *UNTESTED BUT SHOULD WORK FINE*

## **No more problems with autodownload.**

### CODE REVIEW

**Comment by bakawun** [comment]
I had no idea the bug was in that part of the code.

**Comment by Jolty95** [comment]
@bakawun I managed to read the log without the log section enabled (because if log was enabled no error appear in TWLoader ._. very strange isn't it? Now it's finnally solved. It seems my method for read from a file is still valid :P 
I'm working on something more to this PR, hope I can finish it (If I can guess first I to use it...)

**Comment by bakawun** [comment]
I tried to find out why logging fixes it but i could not find any reason for it.

The only thing that caught my eye is this: https://github.com/Robz8/TWLoader/blob/master/gui/source/download.cpp#L193
`if (logEnabled)	LogFM("checkUpdate", "downloadFile() end");`

That end there looks out of place.

**Comment by Jolty95** [comment]
@bakawun that "end" is between " " and it's a const char* so that wasn't the problm. In my research I'm 100% sure that code (the one I have deleted) wasn't reading correctly the ver file that's why it want to redownload. Also, I couldn't find the reason why log enable make it works neither...

**Comment by bakawun** [comment]
Yes i saw it was inside the quotations marks so i did not worry about it

**Comment by Jolty95** [comment]
I need a tester with flashcard to test if searching is working O.K in flashcard and SD!!

**Comment by Robz8** [comment]
The search function only searches for games on my SD Card, even if the location is set to flashcard.

**Comment by Jolty95** [comment]
@Robz8 I don't have any flashcard to test but SD search code is too similar to flashcard. I'll take a look to it in a minutes :)

**Comment by Robz8** [comment]
You don't really need a flashcard to test. I'll send you flashcard game .ini files.

**Comment by Jolty95** [comment]
Yeah, I know what you mean, I forgot that :P

**Comment by Robz8** [comment]
There you go!

[flashcard game ini files.zip](https://github.com/Robz8/TWLoader/files/761576/flashcard.game.ini.files.zip)

**Comment by Robz8** [comment]
I think I found the issue.

**Comment by Jolty95** [comment]
I fixed it :P I'm uploading the changes :)

**Pull request merged**
