### PR TITLE
Implement automatic versioning for the gui

### PR DESCRIPTION
**Pull request by bakawun**
These changes will automatically generate a version number based on the latest tag on git.
This version will be used in the settings screen.

I hope the online version checking still works (just need to remove the ver. from the file) but it should be replaced by a function that checks the git tag instead of downloading the ver file.

### CODE REVIEW

**Comment by bakawun** [comment]
Just to be clear as far as i am concerned this PR is ready to be merged.

**Comment by Robz8** [comment]
I'm now getting
TWLoader/gui/source/main.cpp:1290:66: error: expected primary-expression before ',' token
     snprintf(settings_vertext, 64, "Ver. %d.%d.%d", VERSION_MAJOR, VERSION_MINOR, VERSION_MICRO);

**Comment by Robz8** [comment]
Now I'm getting:

TWLoader/gui/source/main.cpp:1290:66: error: expected primary-expression before ',' token
     snprintf(settings_vertext, 64, "Ver. %d.%d.%d", VERSION_MAJOR, VERSION_MINOR, VERSION_MICRO);

**Comment by tetsuo55** [comment]
looking into it now

**Comment by bakawun** [comment]
That line needs to be in settings.cpp instead of main.cpp, i will send a new pr

**Comment by tetsuo55** [comment]
see https://github.com/Robz8/TWLoader/pull/180

**Comment by bakawun** [comment]
see https://github.com/Robz8/TWLoader/pull/180

**Pull request merged**
